### ISSUE TITLE
waht is hxkj ?

### ISSUE THREAD

**Issue by systemctls** [TangSY/hxkj#3]
I want to know what hxkj means

**Comment by TangSY** [comment]
You can looking for answer from https://hxkj.vip.

**Comment by systemctls** [comment]
Thank you for your reply. I'll check it later




---Original---
From: ***@***.***&gt;
Date: Mon, May 10, 2021 18:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TangSY/hxkj] waht is hxkj ? (#3)




 
You can looking for answer from https://hxkj.vip.
